name: speak_ai
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  flutter_svg: ^2.0.17
  dots_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/conversation1.jpg
    - assets/images/conversation2.jpg
    - assets/images/conversation3.jpg
    - assets/images/lesson.jpg
    - assets/images/topic.jpg
    - assets/images/hanhtinh1.svg
    # Icons
    - assets/icons/list-homework.svg
    - assets/icons/certificate.svg
    - assets/icons/waveform.svg
    - assets/icons/message.svg
    - assets/icons/ai-bot.png
    - assets/icons/scrabble.png
    - assets/icons/crossword.png
    - assets/icons/mic.png
    - assets/icons/voice.svg
    - assets/icons/todolist.svg
    - assets/icons/dictionary.svg
    - assets/icons/filter.svg
    - assets/icons/coach-ai.svg
    - assets/icons/community.svg
    - assets/icons/news.svg
    - assets/icons/book.svg
    - assets/icons/discover.svg
    # Logos
    - assets/logos/ielts-logo.svg
    - assets/logos/elsa-logo.svg

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Condensed-Light.ttf
        - asset: assets/fonts/OpenSans_Condensed-Medium.ttf
        - asset: assets/fonts/OpenSans_Condensed-SemiBold.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Regular.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Bold.ttf
    - family: Amsterdam
      fonts:
        - asset: assets/fonts/Amsterdam.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Light.ttf
        - asset: assets/fonts/Roboto_Condensed-Medium.ttf
        - asset: assets/fonts/Roboto_Condensed-SemiBold.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Bold.ttf
        - asset: assets/fonts/Roboto_SemiCondensed-Regular.ttf
